{
 "title": "AKS/EKS/OCP - Projetos",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "provider", "query": "paas, azure, aws" },
   { "name": "datasource_thanos", "query": "prometheus" },
   { "name": "datasource_elasticsearch", "query": "elasticsearch" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(group(kube_node_labels) by (cluster))"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(group(kube_namespace_labels{cluster=~\"$cluster\"}) by (namespace))"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "query_result(group(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (node))"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "query_result(group(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\"}) by (created_by_kind))"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "query_result(group(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\", created_by_kind=~\"$kind\"}) by (created_by_name))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(group(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\", created_by_kind=~\"$kind\", created_by_name=~\"$name\"}) by (pod))"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(group(container_oom_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"}) by (container))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Sumário Projeto", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quotado Projeto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "Quota Disponivel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace\",type=\"hard\"}) - sum(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace$\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "Memória RSS Utilizada",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespace\",name=~\"k8s_.*\"})\r\nor \r\nsum(container_memory_rss{cluster=\"$cluster\",namespace=~\"$namespace\",name=~\".*\"}) \r\n"
    }
   ]
  },
  {
   "title": "Quota Usada",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\",type=\"used\"}) * 100 / sum(kube_resourcequota{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\",type=\"hard\"})\r\nor\r\nsum(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace$\",type=\"used\"}) * 100 / sum(kube_resourcequota{cluster=~\"$cluster\",namespace=~\"$namespace$\",type=\"hard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Em Execução",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\"})\nor\nsum(kube_pod_container_status_running{cluster=~\"$cluster\",namespace=~\"$namespace$\"})\nor\nsum(kube_running_pod_ready{cluster=~\"$cluster\",namespace=~\"$namespace$\"})"
    }
   ]
  },
  {
   "title": "Quantidade de Restarts Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts{cluster=~\"$cluster\",namespace=~\"$namespace$\"})\nor\nsum(kube_pod_container_status_restarts{cluster=~\"$cluster\",namespace=~\"$namespace$\"})\nor\nsum(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",namespace=~\"$namespace$\"})"
    }
   ]
  },
  {
   "title": "CPU Utilizada",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace$\",container=\"\"}[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória Utilizada",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespace\",name=~\"k8s_.*\"})\r\nor \r\nsum(container_memory_rss{cluster=\"$cluster\",namespace=~\"$namespace\",name=~\".*\"}) "
    }
   ]
  },
  {
   "title": "Estado dos Pods",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\"}) by (phase) > 0\nor\nsum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace$\"}) by (phase) > 0",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\"}) > 0\nor\nsum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace$\"}) > 0",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Quantidade de OOM por containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum(container_oom_events_total{cluster=~\"$cluster\",namespace=~\"$namespace\",node=~\"$node\",pod=~\"$pod\",container=~\"$container\"} > 0)  by (cluster,namespace,node,pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Estado dos Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\"}) by (phase) > 0\nor\nsum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace$\"}) by (phase) > 0",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\"}) > 0\nor\nsum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace$\"}) > 0",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\", phase!=\"Running\"}) by (pod,phase) > 0\nor\nsum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace$\", phase!=\"Running\"}) by (pod,phase) > 0",
     "legendFormat": "{{pod}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Requisições HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requisições",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum((sum_over_time(haproxy_server_connections_total{namespace=~\"$namespace$\"}[5m])))",
       "metrics": [
        {
         "field": "c_ip",
         "id": "1",
         "inlineScript": "namespace",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "namespace.keyword: \"$namespace\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request 2xx",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "namespace:$namespace$ AND namespace:$namespace$",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "namespace.keyword: \"$namespace\" AND status_code: [200 TO 299]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request 5xx",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(sum_over_time(haproxy_server_http_responses_total{namespace=~\"$namespace$\",code!=\"2xx\"}[5m]))",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "namespace.keyword: \"$namespace\" AND status_code: [500 TO 599]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request 4xx",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(sum_over_time(haproxy_server_http_responses_total{namespace=~\"$namespace$\",code!=\"2xx\"}[5m]))",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "namespace.keyword: \"$namespace\" AND status_code: [400 TO 499]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Requisições",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Status Code 2xx",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "namespace.keyword: \"$namespace\" AND status_code : [200 TO 299]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Status Code 3xx",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "namespace.keyword:\"$namespace\" AND status_code : [300 TO 399]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Status Code 4xx",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "namespace.keyword:\"$namespace\" AND status_code : [400 TO 499]",
       "timeField": "@timestamp"
      },
      {
       "alias": "Status Code 5xx",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "count"
        }
       ],
       "query": "namespace.keyword:\"$namespace\" AND status_code : [500 TO 599]",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Ofensores - Erros",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "alias": "Router Name",
       "bucketAggs": [
        {
         "fake": true,
         "field": "router.keyword",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "status_code",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "namespace.keyword: \"$namespace\" AND status_code : [500 TO 599]",
       "timeField": "syslog_time"
      }
     ]
    },
    {
     "title": "Média Tempo Resposta - POD",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "tt",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "namespace.keyword : \"$namespace\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Média Tempo Resposta - Aplicação",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "service.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "tt",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "namespace.keyword: \"$namespace\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Consumo Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Utilização de Memória por Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",namespace=\"$namespace\",image!=\"\",pod=~\"$pod\"}) by (namespace,pod,cluster)",
     "legendFormat": "{{pod}} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Utilização de CPU por Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Milicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\",container=\"\",pod=~\"$pod\"}[5m])) by (pod,cluster)",
     "legendFormat": "{{ pod }} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Consumo de Memória por Pod",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",namespace=\"$namespace\",image!=\"\",pod=~\"$pod\"}) by (pod,cluster)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"deployment\",resource=\"memory\",pod=~\"$pod\"}) by (pod,cluster)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",namespace=\"$namespace\",image!=\"\",pod=~\"$pod\"}) by (pod,cluster) / on (pod,cluster) sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"deployment\",resource=\"memory\",pod=~\"$pod\"}) by (pod,cluster) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumo de CPU por Pod",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\",container=\"\",pod=~\"$pod\"}[5m])) by (pod,cluster), \"pods\", \"$1\", \"pod\", \"(.*)\")"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"deployment\",resource=\"cpu\",pod=~\"$pod\"}) by (pod,cluster)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\",container=\"\",pod=~\"$pod\"}[5m])) by (pod,cluster)\n / on (pod,cluster)\n\nsum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",container!=\"deployment\",resource=\"cpu\",pod=~\"$pod\"}) by (pod,cluster) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Trasmit - Pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes", "label": "Milicores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Network Receiver - Pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes", "label": "Milicores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Image",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Image",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{cluster=~\"$cluster\",exported_namespace=~\"$namespace$\"}) by (container,image,exported_pod)\nor\nsum(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace$\"}) by (container,image,pod)"
      }
     ]
    }
   ]
  },
  { "title": "Pods por Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Pods por Node",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\",namespace=\"$namespace\",node=~\"$node\"}) by (node,pod,pod_ip,host_ip)"
    }
   ]
  }
 ]
}